In [34]:
import pandas as pd
# path = r"C:\Users\Khush\Desktop\Python_Practice_Programs\csv.csv"
df = pd.read_csv('solar.csv')
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South

In [51]:
df['State']

df.loc[len(df)] = ['Jodhpur', 12, 122, 12.2, 122, 'North']

df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South
8,Jodhpur,11,121,12.1,132,North
9,Jodhpur,11,121,12.1,132,North
10,Jodhpur,12,122,12.2,122,North

In [41]:
df.iloc[-1,:]

State                      Jodhpur
Number of Solar Plants          11
Installed Capacity (MW)        121
Average MW Per Plant          12.1
Generation (GWh)               132
Region                       North
Name: 8, dtype: object

In [42]:
df[df['State'] == 'Jodhpur']

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
8,Jodhpur,11,121,12.1,132,North

In [47]:
df[df['State'].isin(['Jodhpur', 'California'])]

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
8,Jodhpur,11,121,12.1,132,North
9,Jodhpur,11,121,12.1,132,North

In [52]:
df_grp = df.groupby('State')
df_grp.value_counts()

State        Number of Solar Plants  Installed Capacity (MW)  Average MW Per Plant  Generation (GWh)  Region
Arizona      48                      1078                     22.5                  2550              West      1
California   289                     4395                     15.3                  10826             West      1
Chicago      33                      261                      7.9                   590               North     1
Connecticut  20                      118                      5.9                   235               East      1
Florida      15                      535                      12.3                  453               South     1
Jodhpur      11                      121                      12.1                  132               North     2
             12                      122                      12.2                  122               North     1
Nevada       11                      238                      21.6                  557               West      1
New York     13                      53                       4.1                   84                East      1
Texas        12                      187                      15.6                  354               South     1
Name: count, dtype: int64

In [54]:
df.sort_values(by='Number of Solar Plants', ascending=False)

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
7,Florida,15,535,12.3,453,South
6,New York,13,53,4.1,84,East
5,Texas,12,187,15.6,354,South
10,Jodhpur,12,122,12.2,122,North
2,Nevada,11,238,21.6,557,West
8,Jodhpur,11,121,12.1,132,North
9,Jodhpur,11,121,12.1,132,North

In [55]:
df.isna()

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False

In [56]:
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South
8,Jodhpur,11,121,12.1,132,North
9,Jodhpur,11,121,12.1,132,North
10,Jodhpur,12,122,12.2,122,North

In [66]:
df.loc[len(df)] = ['Jaisalmer',10,100,10.2,122,'North']
df

,State,Number of Solar Plants,Installed Capacity (MW),Average MW Per Plant,Generation (GWh),Region
0,California,289,4395,15.3,10826,West
1,Arizona,48,1078,22.5,2550,West
2,Nevada,11,238,21.6,557,West
3,Chicago,33,261,7.9,590,North
4,Connecticut,20,118,5.9,235,East
5,Texas,12,187,15.6,354,South
6,New York,13,53,4.1,84,East
7,Florida,15,535,12.3,453,South
8,Jodhpur,11,121,12.1,132,North
9,Jodhpur,11,121,12.1,132,North
10,Jodhpur,12,122,12.2,122,North
11,Jaisalmer,10,100,10.2,122,North
12,Jaisalmer,10,100,10.2,122,North
13,Jaisalmer,10,100,10.2,122,North
14,Jaisalmer,10,100,10.2,122,North

In [67]:
df['State'].apply(len)

0     10
1      7
2      6
3      7
4     11
5      5
6      8
7      7
8      7
9      7
10     7
11     9
12     9
13     9
14     9
Name: State, dtype: int64

In [68]:
df['Installed Capacity (MW)'].map(lambda x:x+100)

0     4495
1     1178
2      338
3      361
4      218
5      287
6      153
7      635
8      221
9      221
10     222
11     200
12     200
13     200
14     200
Name: Installed Capacity (MW), dtype: int64