In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('NumPy_Methods.xlsx - Indexing&Slicing.csv')
df

,"1 D array arr =[1,2,3,4,5,6,7,8,9,10]",Unnamed: 1
0,Basic Indexing,NaN
1,arr[1] => 2,gives element at index 1
2,arr[-1] = >10,gives element at index -1
3,NaN,NaN
4,Slicing [start : end: jump],NaN
5,"arr[1:3] = > [2,3]",gives elements from index 1 uptill 3
6,"arr[0:4:2] => [1,3]",gives alternate elements from index 1 uptill 4
7,"arr[::2]=> [1,3,5,7,9]",gives all alternate elements
8,"arr[-5:-2] => [5,6,7,8]",gives elements from index -5 uptill -2
9,"arr[-2:-5:-1] => [9,8,7,6]",gives elements at index -2 uptill -5 in rever...
10,NaN,NaN
11,Interger Indexing,NaN
12,"arr[[1,4,7]] => [2,5,8]","gives elements at index 1, 4 and 7"
13,NaN,NaN
14,Boolean Indexing,NaN
15,"a1[a1>5] => [6,7,8,9,10]",gives elements where boolean condition is true
16,NaN,NaN
17,NaN,NaN
18,"2D array arr =[[1,2,3][4,5,6] [7,8,9]]",NaN
19,Basic Indexing,NaN
20,"arr [0,2] = 3","gives element at row index 0, col index 2"
21,"arr [1,-1] =6","gives element at row index 1, col index -1"
22,"arr [-2,-1] =3","gives element at row index -2, col index -1"
23,"arr[1] =[4,5,6]",gives subdementional array at row index 1
24,"Slicing [start : end: jump, start : end: jum...",NaN
25,"a2[::2] => ([[1, 2, 3],\n [7, 8, 9]])",NaN
26,"a2[0:,::2] => ([[1, 3],\n [4, 6],\n ...",NaN
27,"a2[::-1] => ([[7, 8, 9],\n [4, 5, 6],\n ...",Row reverse
28,"a2[0:2, 1:] => ([[2, 3],\n [5, 6]])",NaN
29,"a2[0:2, 1::2] => ([[2],\n [5]])",NaN
30,"a2[-3:-1, 2:] => ([[3],\n [6]])",NaN
31,"a2[::2, 1:3] => ([[2, 3],\n [8, 9]])",NaN
32,Interger Indexing : While giving interger inde...,NaN
33,"a2[[0,1,2],[0,1,2]] => ([1, 5, 9])",Selects diagonal elements
34,"a2[[0,0,2,2],[0,2,0,2]] => ([1, 3, 7, 9])",Selects corener elements
35,"a2[[0,2]] => [[1, 2, 3],\n [7, 8, 9]])",Selects sub dimentional arrays by given row in...
36,Boolean Indexing,NaN
37,"a2[a2>5] => ([6, 7, 8, 9])",Gives elements greater than 5
38,"a2[[True,False,True]] => ([[1, 2, 3],\n ...",Gives elements for rows = True
39,"a2[a2 % 2 == 0] => array([2, 4, 6, 8])",Gives even numbers
40,"a2[[True,True,True], [False, True, False]] => ...",Middle elements of all rows
41,"3D array arr =[[[ 0, 1, 2],\n [ 3, 4...",NaN
42,"arr[1] => [[12, 13, 14],\n [15, 16, 17],...",Gives second 2D array from the 3D array
43,"arr[1,1] => [15, 16, 17]",Gives second row from 2nd 2D array
44,"arr[1,1,2] = 17","Gives element at index [1,2] from second 2D array"
45,"arr[-2] => [ 0, 1, 2],\n [ 3, 4, 5],...",1st 2D array from 3D array
46,"arr[-2,-1, -3] => 9","Gives element at index [-1,-3] from first 2D a..."
47,NaN,NaN
48,"Slicing [start : end: jump, start : end: jum...",NaN
49,"arr[::-1] => [[[12, 13, 14],\n [15, 16,...",Reverses the arrays in matrix
50,"arr[:1, ::2, 1:] =>[[[1, 2],\n [7, 8]]]",Gives elements from 1st 2D array all rows (alt...
51,NaN,NaN
52,Interger Indexing : While giving interger inde...,NaN
53,"a3[[0,0,0,0],[0,1,2,3],[1,1,1,1]]",Selects elements at selected positions
54,"i_matrix = [0,0,0,0,1,1,1,1]\ni_row =[0,1,2,3,...",Selects elements at selected positions
55,NaN,NaN
56,Boolean Indexing,NaN
57,a3[a3 % 2==1],Gives all odd numbers from entire 3D array
58,"greater_than_10 = np.where(a3>10, a3,0)\ngreat...","np.where(condition, value_if_true, value_if_fa..."
59,greater_than_5_less_than_15 = np.logical_and(a...,Gives all elements which are greater than 5 an...

In [10]:
df.columns

Index(['1 D array arr =[1,2,3,4,5,6,7,8,9,10]', 'Unnamed: 1'], dtype='object')

In [11]:
df.describe

<bound method NDFrame.describe of                 1 D array arr =[1,2,3,4,5,6,7,8,9,10]  \
0                                     Basic Indexing
1                                         arr[1] => 2
2                                       arr[-1] = >10
3                                                 NaN
4                         Slicing [start : end: jump]
5                                  arr[1:3] = > [2,3]
6                                 arr[0:4:2] => [1,3]
7                              arr[::2]=> [1,3,5,7,9]
8                             arr[-5:-2] => [5,6,7,8]
9                          arr[-2:-5:-1] => [9,8,7,6]
10                                                NaN
11                                  Interger Indexing
12                            arr[[1,4,7]] => [2,5,8]
13                                                NaN
14                                   Boolean Indexing
15                           a1[a1>5] => [6,7,8,9,10]
16                                                NaN
17                                                NaN
18             2D array arr =[[1,2,3][4,5,6] [7,8,9]]
19                                    Basic Indexing
20                                      arr [0,2] = 3
21                                      arr [1,-1] =6
22                                     arr [-2,-1] =3
23                                    arr[1] =[4,5,6]
24  Slicing  [start : end: jump,  start : end: jum...
25        a2[::2] => ([[1, 2, 3],\n       [7, 8, 9]])
26  a2[0:,::2] => ([[1, 3],\n       [4, 6],\n     ...
27  a2[::-1] => ([[7, 8, 9],\n       [4, 5, 6],\n ...
28          a2[0:2, 1:] => ([[2, 3],\n       [5, 6]])
29              a2[0:2, 1::2] => ([[2],\n       [5]])
30              a2[-3:-1, 2:] => ([[3],\n       [6]])
31         a2[::2, 1:3] => ([[2, 3],\n       [8, 9]])
32  Interger Indexing : While giving interger inde...
33                a2[[0,1,2],[0,1,2]] =>  ([1, 5, 9])
34          a2[[0,0,2,2],[0,2,0,2]] => ([1, 3, 7, 9])
35       a2[[0,2]] => [[1, 2, 3],\n       [7, 8, 9]])
36                                   Boolean Indexing
37                         a2[a2>5] => ([6, 7, 8, 9])
38  a2[[True,False,True]] => ([[1, 2, 3],\n       ...
39             a2[a2 % 2 == 0] => array([2, 4, 6, 8])
40  a2[[True,True,True], [False, True, False]] => ...
41  3D array arr =[[[ 0,  1,  2],\n        [ 3,  4...
42  arr[1] => [[12, 13, 14],\n       [15, 16, 17],...
43                           arr[1,1] => [15, 16, 17]
44                                    arr[1,1,2] = 17
45  arr[-2] => [ 0,  1,  2],\n       [ 3,  4,  5],...
46                                arr[-2,-1, -3] => 9
47                                                NaN
48  Slicing  [start : end: jump,  start : end: jum...
49  arr[::-1] => [[[12, 13, 14],\n        [15, 16,...
50     arr[:1, ::2, 1:] =>[[[1, 2],\n        [7, 8]]]
51                                                NaN
52  Interger Indexing : While giving interger inde...
53                  a3[[0,0,0,0],[0,1,2,3],[1,1,1,1]]
54  i_matrix = [0,0,0,0,1,1,1,1]\ni_row =[0,1,2,3,...
55                                                NaN
56                                   Boolean Indexing
57                                      a3[a3 % 2==1]
58  greater_than_10 = np.where(a3>10, a3,0)\ngreat...
59  greater_than_5_less_than_15 = np.logical_and(a...

                                           Unnamed: 1
0                                                 NaN
1                            gives element at index 1
2                           gives element at index -1
3                                                 NaN
4                                                 NaN
5                gives elements from index 1 uptill 3
6      gives alternate elements from index 1 uptill 4
7                        gives all alternate elements
8              gives elements from index -5 uptill -2
9   gives elements  at index -2 uptill -5 in rever...
10                                                NaN
11                                                NaN
12                 gives elements at index 1, 4 and 7
13                                                NaN
14                                                NaN
15     gives elements where boolean condition is true
16                                                NaN
17                                                NaN
18                                                NaN
19                                                NaN
20          gives element at row index 0, col index 2
21         gives element at row index 1, col index -1
22        gives element at row index -2, col index -1
23          gives subdementional array at row index 1
24                                                NaN
25                                                NaN
26                                                NaN
27                                        Row reverse
28                                                NaN
29                                                NaN
30                                                NaN
31                                                NaN
32                                                NaN
33                          Selects diagonal elements
34                           Selects corener elements
35  Selects sub dimentional arrays by given row in...
36                                                NaN
37                      Gives elements greater than 5
38                     Gives elements for rows = True
39                                 Gives even numbers
40                        Middle elements of all rows
41                                                NaN
42            Gives second 2D array from the 3D array
43                 Gives second row from 2nd 2D array
44  Gives element at index [1,2] from second 2D array
45                         1st 2D array from 3D array
46  Gives element at index [-1,-3] from first 2D a...
47                                                NaN
48                                                NaN
49                      Reverses the arrays in matrix
50  Gives elements from 1st 2D array all rows (alt...
51                                                NaN
52                                                NaN
53             Selects elements at selected positions
54             Selects elements at selected positions
55                                                NaN
56                                                NaN
57         Gives all odd numbers from entire 3D array
58  np.where(condition, value_if_true, value_if_fa...
59  Gives all elements which are greater than 5 an...  >

In [13]:
df.describe().map(lambda x:'BaseIndex')

       1 D array arr =[1,2,3,4,5,6,7,8,9,10] Unnamed: 1
count                              BaseIndex  BaseIndex
unique                             BaseIndex  BaseIndex
top                                BaseIndex  BaseIndex
freq                               BaseIndex  BaseIndex

In [14]:
df.loc[26]

1 D array arr =[1,2,3,4,5,6,7,8,9,10]    a2[0:,::2] => ([[1, 3],\n       [4, 6],\n     ...
Unnamed: 1                                                                             NaN
Name: 26, dtype: object

In [21]:
df.loc[[25,26,58]]

,"1 D array arr =[1,2,3,4,5,6,7,8,9,10]",Unnamed: 1
25,"a2[::2] => ([[1, 2, 3],\n [7, 8, 9]])",NaN
26,"a2[0:,::2] => ([[1, 3],\n [4, 6],\n ...",NaN
58,"greater_than_10 = np.where(a3>10, a3,0)\ngreat...","np.where(condition, value_if_true, value_if_fa..."

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 2 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   1 D array arr =[1,2,3,4,5,6,7,8,9,10]  52 non-null     object
 1   Unnamed: 1                             33 non-null     object
dtypes: object(2)
memory usage: 1.1+ KB