In [1]:
import pandas as pd
names = ['riya', 'priya', 'nikhu', 'ram']
series_n = pd.Series(names)
series_n

0     riya
1    priya
2    nikhu
3      ram
dtype: object

In [3]:
series_n.values

array(['riya', 'priya', 'nikhu', 'ram'], dtype=object)

In [4]:
count = {'usa':50, 'india': 40, 'uk':90, 'france':90}
count = pd.Series(count)
count

usa       50
india     40
uk        90
france    90
dtype: int64

In [6]:
count.loc['india']

np.int64(40)

In [5]:
count.iloc[1]

np.int64(40)

In [8]:
head = pd.Series({'usa':'nyc', 'india': 'pune', 'uk':'london', 'france':'paris'})
head

usa          nyc
india       pune
uk        london
france     paris
dtype: object

In [10]:
# combining series data- should have same indices
df = pd.DataFrame({'Head Office': head, 'Employee Count':count})
df

       Head Office  Employee Count
usa            nyc              50
india         pune              40
uk          london              90
france       paris              90

In [ ]:
#===== end index is also included here!!=====
df.loc['india':'france']

       Head Office  Employee Count
india         pune              40
uk          london              90
france       paris              90

In [13]:
df.loc['india':'france', 'Head Office	' : 'Employee Count']

       Head Office  Employee Count
india         pune              40
uk          london              90
france       paris              90

In [ ]:
df.iloc[1:3, [0,1]]
#loc should have only labeled index, only if index is not given, then it takes integer as an index

      Head Office  Employee Count
india        pune              40
uk         london              90

In [18]:
data = {'name':['riya', 'priya', 'nikhu', 'ram'], 
        'salary' : [30000,40000,50000,60000],
        'dept' : ['Admin', 'it', 'it', 'hr']}

df = pd.DataFrame(data)
df

    name  salary   dept
0   riya   30000  Admin
1  priya   40000     it
2  nikhu   50000     it
3    ram   60000     hr

In [19]:
df.set_index('name')
df

    name  salary   dept
0   riya   30000  Admin
1  priya   40000     it
2  nikhu   50000     it
3    ram   60000     hr

In [ ]:
#data - row data, index = labelled indeiced, columns = col header
# df is a collection of multiple
df = pd.DataFrame(data=[[500,35,23], [600,40,34], [300,34,23]] ,
                   index = ['tata', 'maruti','honda'],
                  columns = ['Revenue', 'market share', 'profit'])

df

        Revenue  market share  profit
tata        500            35      23
maruti      600            40      34
honda       300            34      23

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, tata to honda
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Revenue       3 non-null      int64
 1   market share  3 non-null      int64
 2   profit        3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes